/* ===== Axé de Quitéria — Loja (catálogo) =====
   Espelha a tabela `produtos` do Supabase compartilhado com a gestão.
   Campos: id, nome, slug, categoria, preco, preco_antigo, destaque,
           badge, orixa, materiais[], cores[] (motivo visual), fundamento,
           descricao, variantes[], avaliacao, num_avaliacoes, estoque
*/

const LJ_CATEGORIES = [
  { id:'guias',       name:'Guias de Proteção', icon:'guia',     desc:'Axé e proteção no pescoço' },
  { id:'fios',        name:'Guias de trabalho',  icon:'beads',    desc:'Sua corrente sempre com você' },
  { id:'ferramentas', name:'Velas',              icon:'candle',   desc:'Acenda sua intenção' },
  { id:'pulseiras',   name:'Pulseiras',          icon:'bracelet', desc:'Um toque de fé no pulso' },
  { id:'braceletes',  name:'Braceletes',         icon:'bangle',   desc:'Metais que afirmam força' },
  { id:'patua',       name:'Patuás',             icon:'patua',    desc:'Seu amuleto de guarda' },
  { id:'vestuario',   name:'Vestuário',          icon:'shirt',    desc:'Vista a tradição com elegância' },
  { id:'chapeus',     name:'Chapéus',            icon:'hat',      desc:'Coroe e proteja o orí' },
  { id:'banhos',      name:'Banhos & Ervas',     icon:'leaf',     desc:'Limpeza e caminhos abertos' },
];

const LJ_PRODUCTS = [
  {
    id:'gp-oxum', nome:'Guia de Oxum Lapidada', slug:'guia-oxum-lapidada',
    categoria:'guias', preco:189.00, preco_antigo:230.00, destaque:true, badge:'Mais vendida',
    orixa:'Oxum', cores:['#E8C86B','#F2E2B0','#D9A93C'], tom:'#FBF3DF',
    avaliacao:4.9, num_avaliacoes:38, estoque:6,
    materiais:['Cristais lapidados','Pérolas','Firma dourada','Fio encerado'],
    fundamento:'Oxum rege as águas doces, o ouro e o amor-próprio. Esta guia é montada fio a fio com axé, ideal para quem busca prosperidade e acolhimento.',
    descricao:'Cada conta é selecionada e lapidada à mão. O dourado das firmas reflete a riqueza da Senhora das Cachoeiras.',
    variantes:[
      { label:'Tamanho', options:['Curta (50cm)','Média (60cm)','Longa (70cm)'] },
      { label:'Firma', options:['Dourada','Cristal','Madrepérola'] },
    ],
  },
  {
    id:'gp-ogum', nome:'Guia de Ogum 7 Fios', slug:'guia-ogum-7-fios',
    categoria:'guias', preco:245.00, preco_antigo:null, destaque:true, badge:'Premium',
    orixa:'Ogum', cores:['#2F5D46','#1E3F30','#3E7B5A'], tom:'#EAF0EB',
    avaliacao:5.0, num_avaliacoes:21, estoque:3,
    materiais:['Contas verdes leitosas','Elo de ferro','Cordão São Francisco'],
    fundamento:'Ogum é o senhor dos caminhos e da força. Sete fios para abrir estradas e proteger o guerreiro em todas as batalhas.',
    descricao:'Montada com elos que remetem ao ferro de Ogum. Peça robusta, de presença firme.',
    variantes:[
      { label:'Tamanho', options:['Média (60cm)','Longa (70cm)'] },
      { label:'Acabamento', options:['Fosco','Brilhante'] },
    ],
  },
  {
    id:'gp-iemanja', nome:'Brajá de Iemanjá', slug:'braja-iemanja',
    categoria:'guias', preco:320.00, preco_antigo:null, destaque:true, badge:null,
    orixa:'Iemanjá', cores:['#BFD6E6','#EAF2F7','#8FB7CF'], tom:'#EEF4F8',
    avaliacao:4.8, num_avaliacoes:14, estoque:2,
    materiais:['Contas cristal','Madrepérola','Búzios','Firma prateada'],
    fundamento:'A Mãe das Águas Salgadas, rainha do mar. O brajá traz serenidade, fertilidade e proteção materna.',
    descricao:'Peça de alto fundamento com búzios naturais e madrepérola. Acabamento prateado.',
    variantes:[
      { label:'Tamanho', options:['Média (60cm)','Longa (75cm)'] },
      { label:'Búzios', options:['3 búzios','5 búzios','7 búzios'] },
    ],
  },
  {
    id:'gp-xango', nome:'Guia de Xangô', slug:'guia-xango',
    categoria:'guias', preco:198.00, preco_antigo:240.00, destaque:false, badge:'Oferta',
    orixa:'Xangô', cores:['#9B3022','#C75B43','#6E2017'], tom:'#F6E7E1',
    avaliacao:4.7, num_avaliacoes:11, estoque:5,
    materiais:['Contas marrom e vermelho','Pedra','Machado duplo'],
    fundamento:'Xangô é a justiça e o fogo. Sua guia equilibra força e razão, trazendo respeito e liderança.',
    descricao:'Tons terrosos de marrom e vermelho com a insígnia do oxê (machado duplo).',
    variantes:[{ label:'Tamanho', options:['Curta (50cm)','Média (60cm)'] }],
  },
  {
    id:'gp-iansa', nome:'Guia de Iansã', slug:'guia-iansa',
    categoria:'guias', preco:176.00, preco_antigo:null, destaque:false, badge:null,
    orixa:'Iansã', cores:['#B5453A','#E0A86A','#8E2E27'], tom:'#F7EBE2',
    avaliacao:4.9, num_avaliacoes:9, estoque:7,
    materiais:['Contas vermelho e coral','Cristal','Firma cobre'],
    fundamento:'Senhora dos ventos e tempestades. Iansã traz coragem, movimento e a força para encarar mudanças.',
    descricao:'Vermelho vibrante com toques de coral. Energia em movimento.',
    variantes:[{ label:'Tamanho', options:['Média (60cm)','Longa (70cm)'] }],
  },
  {
    id:'fc-cristal', nome:'Fio de Cristal 6mm (1m)', slug:'fio-cristal-6mm',
    categoria:'fios', preco:34.00, preco_antigo:null, destaque:true, badge:null,
    orixa:null, cores:['#DCEBF0','#F1ECE2','#C9D8DE'], tom:'#F2F6F8',
    avaliacao:4.6, num_avaliacoes:27, estoque:40,
    materiais:['Cristal transparente 6mm','Fio resistente'],
    fundamento:'Matéria-prima para suas próprias montagens, com a qualidade do ateliê.',
    descricao:'Um metro de cristais 6mm transparentes, prontos para enfiar.',
    variantes:[{ label:'Cor', options:['Transparente','Leitoso','Âmbar'] }],
  },
  {
    id:'fc-perola', nome:'Fio de Pérolas (1m)', slug:'fio-perolas',
    categoria:'fios', preco:28.00, preco_antigo:null, destaque:false, badge:null,
    orixa:null, cores:['#EDE6D8','#F6F1E7','#DCD2BE'], tom:'#F7F3EA',
    avaliacao:4.8, num_avaliacoes:33, estoque:55,
    materiais:['Pérola acetinada','Fio encerado'],
    fundamento:'Pérolas clássicas para guias de Oxum, Iemanjá e Nanã.',
    descricao:'Um metro de pérolas acetinadas de tom marfim.',
    variantes:[{ label:'Tom', options:['Marfim','Branco','Rosé'] }],
  },
  {
    id:'fr-oxe', nome:'Oxê de Xangô (Ferramenta)', slug:'oxe-xango',
    categoria:'ferramentas', preco:96.00, preco_antigo:null, destaque:true, badge:'Artesanal',
    orixa:'Xangô', cores:['#9A6B3F','#C9A24B','#6E4A2A'], tom:'#F3EADB',
    avaliacao:5.0, num_avaliacoes:8, estoque:4,
    materiais:['Madeira nobre','Acabamento dourado'],
    fundamento:'O machado duplo de Xangô, símbolo da justiça que corta para os dois lados.',
    descricao:'Insígnia entalhada em madeira com detalhe dourado. Para altares e assentamentos.',
    variantes:[{ label:'Tamanho', options:['Pequeno (15cm)','Médio (22cm)'] }],
  },
  {
    id:'fr-ferramenta-ogum', nome:'Ferramenta de Ogum', slug:'ferramenta-ogum',
    categoria:'ferramentas', preco:120.00, preco_antigo:null, destaque:false, badge:null,
    orixa:'Ogum', cores:['#3E4A42','#6E7B72','#2A332D'], tom:'#ECEEEC',
    avaliacao:4.9, num_avaliacoes:6, estoque:3,
    materiais:['Metal forjado','Base de madeira'],
    fundamento:'Espada, enxada e ferramentas de Ogum em metal — o senhor da tecnologia e dos caminhos.',
    descricao:'Conjunto de 7 ferramentas em metal sobre suporte. Peça de assentamento.',
    variantes:[{ label:'Peças', options:['7 ferramentas','14 ferramentas'] }],
  },
  {
    id:'bn-descarrego', nome:'Banho de Descarrego', slug:'banho-descarrego',
    categoria:'banhos', preco:42.00, preco_antigo:null, destaque:true, badge:'Novo',
    orixa:null, cores:['#5E7E5A','#9CB58C','#3F5A3B'], tom:'#EDF1EA',
    avaliacao:4.7, num_avaliacoes:19, estoque:30,
    materiais:['Arruda','Guiné','Espada de São Jorge','Sal grosso'],
    fundamento:'Ervas de corte para limpar energias densas e abrir o corpo para o bem.',
    descricao:'Kit de ervas secas selecionadas, com modo de uso. Rende 3 banhos.',
    variantes:[{ label:'Quantidade', options:['1 kit (3 banhos)','3 kits'] }],
  },
  {
    id:'bn-prosperidade', nome:'Banho de Prosperidade', slug:'banho-prosperidade',
    categoria:'banhos', preco:46.00, preco_antigo:null, destaque:false, badge:null,
    orixa:'Oxum', cores:['#E8C86B','#F0DDA0','#C99B33'], tom:'#FBF4E0',
    avaliacao:4.8, num_avaliacoes:24, estoque:28,
    materiais:['Macela','Girassol','Canela','Mel'],
    fundamento:'Ervas de atração e doçura, regidas por Oxum, para abrir caminhos de fartura.',
    descricao:'Ervas aromáticas com canela e pétalas. Rende 3 banhos.',
    variantes:[{ label:'Quantidade', options:['1 kit (3 banhos)','3 kits'] }],
  },

  // ---- Pulseiras ----
  {
    id:'pl-oxum', nome:'Pulseira de Oxum', slug:'pulseira-oxum',
    categoria:'pulseiras', preco:58.00, preco_antigo:null, destaque:true, badge:null,
    orixa:'Oxum', cores:['#E8C86B','#F2E2B0','#D9A93C'], tom:'#FBF3DF',
    avaliacao:4.9, num_avaliacoes:17, estoque:14,
    materiais:['Cristais dourados','Firma','Elástico de seda'],
    fundamento:'Leve a doçura e a prosperidade de Oxum no pulso, todos os dias.',
    descricao:'Pulseira ajustável com cristais dourados e firma central.',
    variantes:[{ label:'Tamanho', options:['P','M','G'] }],
  },
  {
    id:'pl-protecao', nome:'Pulseira de Proteção (Olho Grego)', slug:'pulseira-protecao',
    categoria:'pulseiras', preco:46.00, preco_antigo:62.00, destaque:false, badge:'Oferta',
    orixa:null, cores:['#5B7B96','#BFD6E6','#2A4A63'], tom:'#EAF1F6',
    avaliacao:4.8, num_avaliacoes:29, estoque:22,
    materiais:['Olho grego','Contas azuis','Fio resistente'],
    fundamento:'O olho grego afasta o mau-olhado e guarda quem você ama.',
    descricao:'Pulseira com amuleto de olho grego e contas azuis.',
    variantes:[{ label:'Tamanho', options:['P','M','G'] }],
  },
  {
    id:'pl-7orixas', nome:'Pulseira 7 Orixás', slug:'pulseira-7-orixas',
    categoria:'pulseiras', preco:72.00, preco_antigo:null, destaque:false, badge:'Artesanal',
    orixa:null, cores:['#B0542F','#566B49','#B0892E'], tom:'#F3EADB',
    avaliacao:5.0, num_avaliacoes:11, estoque:9,
    materiais:['Contas das 7 cores','Firmas','Elástico'],
    fundamento:'As cores dos sete orixás reunidas para proteção completa.',
    descricao:'Pulseira com as contas representando os sete orixás de cabeça.',
    variantes:[{ label:'Tamanho', options:['P','M','G'] }],
  },

  // ---- Braceletes (metal/rígido) ----
  {
    id:'br-ogum', nome:'Bracelete de Ogum (Idé)', slug:'bracelete-ogum-ide',
    categoria:'braceletes', preco:88.00, preco_antigo:null, destaque:true, badge:null,
    orixa:'Ogum', cores:['#566B49','#7E8B6B','#3E4A36'], tom:'#ECEFE8',
    avaliacao:4.9, num_avaliacoes:12, estoque:10,
    materiais:['Metal banhado','Acabamento fosco'],
    fundamento:'O idé de Ogum em metal, símbolo de força e abertura de caminhos no pulso.',
    descricao:'Bracelete rígido ajustável em metal, leve e resistente.',
    variantes:[{ label:'Acabamento', options:['Prateado','Dourado','Cobre'] }],
  },
  {
    id:'br-oxum', nome:'Bracelete de Oxum (Dourado)', slug:'bracelete-oxum-dourado',
    categoria:'braceletes', preco:96.00, preco_antigo:120.00, destaque:false, badge:'Oferta',
    orixa:'Oxum', cores:['#C9A24B','#E8C86B','#A57E2A'], tom:'#FBF3DF',
    avaliacao:5.0, num_avaliacoes:9, estoque:7,
    materiais:['Metal banhado a ouro','Detalhe em corações'],
    fundamento:'O ouro de Oxum no pulso: prosperidade, beleza e amor-próprio.',
    descricao:'Bracelete dourado com gravação delicada. Fecho ajustável.',
    variantes:[{ label:'Largura', options:['Fino','Médio','Largo'] }],
  },
  {
    id:'br-conjunto', nome:'Conjunto de Argolas Africanas', slug:'argolas-africanas',
    categoria:'braceletes', preco:74.00, preco_antigo:null, destaque:false, badge:'Artesanal',
    orixa:null, cores:['#B0542F','#C9A24B','#7A2A24'], tom:'#F4E5DC',
    avaliacao:4.8, num_avaliacoes:15, estoque:14,
    materiais:['Metal','Resina colorida'],
    fundamento:'Conjunto de argolas inspirado nos adornos da diáspora africana.',
    descricao:'Trio de braceletes para usar juntos ou separados.',
    variantes:[{ label:'Cor', options:['Terra','Dourado','Multicor'] }],
  },

  // ---- Patuás (amuletos de guarda) ----
  {
    id:'pt-guarda', nome:'Patuá de Guarda', slug:'patua-de-guarda',
    categoria:'patua', preco:68.00, preco_antigo:null, destaque:true, badge:'Mais vendido',
    orixa:null, cores:['#7A2A24','#B0542F','#4A1712'], tom:'#F4E5DC',
    avaliacao:5.0, num_avaliacoes:22, estoque:16,
    materiais:['Couro/tecido','Cordão encerado','Enchimento de ervas'],
    fundamento:'O patuá guarda o que protege: ervas e firmezas costuradas para andar com você.',
    descricao:'Bolsinha amuleto preparada e fechada à mão, para usar no pescoço.',
    variantes:[{ label:'Cor', options:['Vermelho','Preto','Branco'] }],
  },
  {
    id:'pt-corpo-fechado', nome:'Patuá Corpo Fechado', slug:'patua-corpo-fechado',
    categoria:'patua', preco:84.00, preco_antigo:null, destaque:false, badge:null,
    orixa:'Ogum', cores:['#566B49','#3E4A36','#7E8B6B'], tom:'#ECEFE8',
    avaliacao:4.9, num_avaliacoes:11, estoque:9,
    materiais:['Couro','Medalha de Ogum','Ervas de proteção'],
    fundamento:'Para fechar o corpo contra energias densas, sob a força de Ogum.',
    descricao:'Patuá com medalha e firmezas de corpo fechado.',
    variantes:[{ label:'Cordão', options:['Couro','Encerado preto','Corrente'] }],
  },
  {
    id:'pt-prosperidade', nome:'Patuá da Prosperidade', slug:'patua-prosperidade',
    categoria:'patua', preco:72.00, preco_antigo:92.00, destaque:false, badge:'Oferta',
    orixa:'Oxum', cores:['#C9A24B','#E8C86B','#A57E2A'], tom:'#FBF3DF',
    avaliacao:4.8, num_avaliacoes:18, estoque:13,
    materiais:['Tecido dourado','Sementes','Ervas de Oxum'],
    fundamento:'Doçura e fartura de Oxum guardadas para atrair caminhos de prosperidade.',
    descricao:'Patuá dourado com sementes e ervas de atração.',
    variantes:[{ label:'Cor', options:['Dourado','Amarelo','Verde'] }],
  },

  // ---- Vestuário ----
  {
    id:'vs-bata', nome:'Bata de Renda Branca', slug:'bata-renda-branca',
    categoria:'vestuario', preco:189.00, preco_antigo:null, destaque:true, badge:null,
    orixa:'Oxalá', cores:['#F6F1E7','#EDE6D8','#DCD2BE'], tom:'#FAF6EE',
    avaliacao:4.9, num_avaliacoes:13, estoque:8,
    materiais:['Algodão','Renda renascença'],
    fundamento:'O branco de Oxalá: paz, fé e a roupa de festa dos terreiros.',
    descricao:'Bata em algodão leve com acabamento em renda renascença.',
    variantes:[{ label:'Tamanho', options:['P','M','G','GG'] }],
  },
  {
    id:'vs-saia', nome:'Saia de Baiana Rodada', slug:'saia-baiana',
    categoria:'vestuario', preco:240.00, preco_antigo:280.00, destaque:false, badge:'Oferta',
    orixa:null, cores:['#F6F1E7','#E8C86B','#EDE6D8'], tom:'#FAF6EE',
    avaliacao:5.0, num_avaliacoes:7, estoque:5,
    materiais:['Algodão engomado','Bordado','Renda'],
    fundamento:'A saia rodada das baianas, tradição que roda com axé.',
    descricao:'Saia ampla com anágua, bordado e barra em renda.',
    variantes:[{ label:'Tamanho', options:['Único','Sob medida'] }],
  },
  {
    id:'vs-pano', nome:'Pano da Costa', slug:'pano-da-costa',
    categoria:'vestuario', preco:96.00, preco_antigo:null, destaque:false, badge:null,
    orixa:null, cores:['#B0542F','#C9A24B','#566B49'], tom:'#F3EADB',
    avaliacao:4.7, num_avaliacoes:10, estoque:12,
    materiais:['Tecido africano','Acabamento manual'],
    fundamento:'O pano da costa, usado sobre os ombros, marca de respeito e tradição.',
    descricao:'Pano da costa em tecido de inspiração africana.',
    variantes:[{ label:'Estampa', options:['Terra','Dourada','Verde'] }],
  },

  // ---- Chapéus / coberturas ----
  {
    id:'ch-turbante', nome:'Turbante Estampado', slug:'turbante-estampado',
    categoria:'chapeus', preco:64.00, preco_antigo:null, destaque:true, badge:'Mais vendido',
    orixa:null, cores:['#B0542F','#C9A24B','#7A2A24'], tom:'#F4E5DC',
    avaliacao:4.9, num_avaliacoes:34, estoque:18,
    materiais:['Tecido africano','Forro de algodão'],
    fundamento:'Coroa de pano: o turbante eleva e protege a coroa (orí).',
    descricao:'Turbante pré-amarrado, fácil de vestir, em estampa exclusiva.',
    variantes:[{ label:'Estampa', options:['Terracota','Dourada','Índigo'] }],
  },
  {
    id:'ch-oja', nome:'Ojá / Torço Branco', slug:'oja-torco-branco',
    categoria:'chapeus', preco:38.00, preco_antigo:null, destaque:false, badge:null,
    orixa:'Oxalá', cores:['#F6F1E7','#EDE6D8','#DCD2BE'], tom:'#FAF6EE',
    avaliacao:4.8, num_avaliacoes:15, estoque:25,
    materiais:['Algodão branco'],
    fundamento:'O ojá branco amarra a cabeça para os trabalhos e festas de Oxalá.',
    descricao:'Faixa de tecido branco para amarração da cabeça.',
    variantes:[{ label:'Comprimento', options:['1,5m','2,5m'] }],
  },
];

// Frete simulado (a integração real calcula por CEP no backend)
const LJ_SHIPPING = [
  { id:'retirada', label:'Retirar na loja',   sub:'Porto Alegre, RS — grátis', value:0, prazo:'Hoje' },
  { id:'sedex',    label:'SEDEX',             sub:'Todo o Brasil',              value:28.50, prazo:'2–4 dias úteis' },
  { id:'motoboy',  label:'Entrega expressa',  sub:'Porto Alegre e região',      value:15.00, prazo:'Hoje/amanhã' },
];

// Dados da loja (compartilhados com a gestão)
const LJ_STORE = {
  nome:'Axé de Quitéria',
  cidade:'Porto Alegre, RS',
  endereco:'Rua dos Andradas, 1234 — Centro Histórico',
  whatsapp:'5551996813336',          // só dígitos, com DDI 55
  whatsapp_label:'(51) 99681-3336',
  pix:'axedequiteria@pix.com.br',
  instagram:'@axedequiteria',
};

Object.assign(window, { LJ_CATEGORIES, LJ_PRODUCTS, LJ_SHIPPING, LJ_STORE });
